#### PLATFORM TRANSACTION SERVICE APPLICATION TEST CONFIGURATIONS

## SSL CONFIGURATIONS
server:
  ssl:
    enabled: true
    key-alias: aeusapp
    key-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
    key-store: /platform/certs/aeusapp-keystore.jks
    key-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
    trust-store: /platform/certs/aeusapp-truststore.jks
    trust-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)


## REST CLIENT SSL CONFIGURATIONS
rest:
  client:
    ssl:
      enabled: true
      key-alias: aeusapp
      key-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
      key-store: /platform/certs/aeusapp-keystore.jks
      key-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
      trust-store: /platform/certs/aeusapp-truststore.jks
      trust-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)


## SPRING CONFIGURATIONS
spring:
  # ZIPKIN CONFIGURATIONS
  zipkin:
      baseUrl: https://monitor.aeus.davinta.com:5000

  # CONSUL CONFIGURATIONS
  cloud:
    consul:
      host: consul.aeus.davinta.com
      port: 8500

  # DATASOURCE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://mysql.aeus.davinta.com:3306/platform_groupmanagement?useSSL=false
    username: platform_groupmanagement_user
    password: Platform@GroupManagement123


## REDIS CONFIGURATIONS
redis:
  server:
    host: redis.aeus.davinta.com
    port: 6379
    password: ENC(402B1482EA0F7039B0D95CA514944870CE1655D218E8EAC51F1A0AF7356CB749BACBB8CC12AADD1B39078525ED3A484E4B9603D249A2CE1261875FCFA0D4FDDF3383938253377A218FA82063205EE10153730AE5D792F2A62FAAF3AB70C2C87725819FF39324568E2A9D826A64135890A9B7BFAE4E99479C471A1C0DCD016AB5EDEE45E3BD9B5DB7727CCE49C98A9A41)
    password.enabled: true


## TRANSACTION CONFIGURATIONS
transaction:
  aualicense:
    auaCode: STGSYND001
    subAuaCode: STGSYND001
    auaLicenseKey: ENC(A8C62728C08C14E62E1619A08A37ACE71089900A93989D5E501560367748745CBC75672C9F4AE279C1F0777E3C77FC98C28FC3E7ABC472605F79B87CD01E8585)


## SERVICE CONFIGURATIONS
AdminService:
  url: https://admin.aeus.davinta.com:5300
EnrollmentService:
  url: https://admin.aeus.davinta.com:5600
FamilySurveyService:
  url: https://admin.aeus.davinta.com:6200
