#### PLATFORM GROUPMANAGEMENT SERVICE APPLICATION DEFAULT CONFIGURATIONS

## SSL CONFIGURATIONS
server:
  ssl:
    enabled: false
    key-alias: aeusapp
    key-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
    key-store: D:/platform/certs/aeusapp-keystore.jks
    key-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
    trust-store: D:/platform/certs/aeusapp-truststore.jks
    trust-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)


## REST CLIENT SSL CONFIGURATIONS
rest:
  client:
    ssl:
      enabled: false
      key-alias: aeusapp
      key-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
      key-store: D:/platform/certs/aeusapp-keystore.jks
      key-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)
      trust-store: D:/platform/certs/aeusapp-truststore.jks
      trust-store-password: ENC(42039B89B9855AB0FF016ABAF3D1718BDE2B3F3093845587)


## SPRING CONFIGURATIONS
spring:
  # ZIPKIN CONFIGURATIONS
  zipkin:
      baseUrl: http://localhost:5000

  ## SLEUTH CONFIGURATIONS
  sleuth:
    enabled: false

  # CONSUL CONFIGURATIONS
  cloud:
    consul:
      host: 192.168.56.101
      port: 8500

  # DATASOURCE CONFIGURATIONS
  datasource:
    url: jdbc:mysql://192.168.56.101:6033/platform_groupmanagement?useSSL=false
    username: root
    password: ENC(080182C61D6D2F34E88A7CA8DEB4D50600802DC921636ABB)


## REDIS CONFIGURATIONS
redis:
  server:
    host: 192.168.56.101
    port: 6379
    password: ENC(402B1482EA0F7039B0D95CA514944870CE1655D218E8EAC51F1A0AF7356CB749BACBB8CC12AADD1B39078525ED3A484E4B9603D249A2CE1261875FCFA0D4FDDF3383938253377A218FA82063205EE10153730AE5D792F2A62FAAF3AB70C2C87725819FF39324568E2A9D826A64135890A9B7BFAE4E99479C471A1C0DCD016AB5EDEE45E3BD9B5DB7727CCE49C98A9A41)
    password.enabled: true


## TRANSACTION CONFIGURATIONS
transaction:
  aualicense:
    auaCode: STGSYND001
    subAuaCode: STGSYND001
    auaLicenseKey: ENC(D730344C165A24967DB3F57165744F1D4F623D6BC1961FEA9DAAC522DF1EBA24C6EB8C4B65D3AA28766AD12E11899AC46B1B32CA6555D5B5A8463A3BF38EDD4B)


## SERVICE CONFIGURATIONS
AdminService:
  url: http://localhost:5300
EnrollmentService:
  url: http://localhost:5600
FamilySurveyService:
  url: http://localhost:6200
